version: "3.8"
services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresProject01*
    ports:
      - "5430:5432"
    volumes:
      - db:/var/lib/postgresql/data

  jasperreports:
    image: docker.io/bitnami/jasperreports:8
    ports:
      - "8089:8080"
    volumes:
      - 'jasperreports_data:/bitnami/jasperreports'
    depends_on:
      - db
    environment:
      - JASPERREPORTS_DATABASE_TYPE=postgresql
      - JASPERREPORTS_DATABASE_HOST=db
      - JASPERREPORTS_DATABASE_PORT_NUMBER=5432
      - JASPERREPORTS_DATABASE_USER=postgres
      - JASPERREPORTS_DATABASE_PASSWORD=postgresProject01*
      - JASPERREPORTS_DATABASE_NAME=postgres
      - JASPERREPORTS_USERNAME=jasperadmin
      - JASPERREPORTS_PASSWORD=jasperadminProject01*

volumes:
  db:
    driver: local
  jasperreports_data:
    driver: local