version: "3.2"
services:
  rabbitmq:
    build: .
    container_name: 'rabbitmq'
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
networks:
  rabbitmq_go_net:
    driver: bridge
volumes:
  rabbitmq_data:
  rabbitmq_log: