version: '3.8'
services:
  az:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '10000:10000'
      - '10001:10001'
      - '10002:10002'
volumes:
  az:
    driver: local