version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6479:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass yourpasswordforredis
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local